package limine

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

const sampleLimineConf = `#timeout: 3
default_entry: 2
interface_branding: Omarchy Bootloader
interface_branding_color: 2
hash_mismatch_panic: no

term_background: 1a1b26
backdrop: 1a1b26

/+Omarchy
### This OS entry is auto-generated by limine-entry-tool
comment: Omarchy
comment: machine-id=c4f25e56 order-priority=50
  //linux
  comment: Kernel version: 6.19.10-arch1-1
  comment: kernel-id=linux
  protocol: efi
  path: boot():/EFI/Linux/omarchy_linux.efi
  cmdline: rw quiet

     //Snapshots
     ### Auto-generated by limine-snapper-sync
     comment: 2 / 2 snapshots
     ///2026-04-14 15:00:02
     comment: timeline
     ////linux
     comment: Kernel version: 6.19.10-arch1-1
     comment: kernel-id=linux
     protocol: efi
     path: boot():/something
     cmdline: quiet rootflags=subvol=/@/.snapshots/98/snapshot rw
     ///2026-04-14 14:00:06
     comment: pre
     ////linux
     comment: Kernel version: 6.19.10-arch1-1
     comment: kernel-id=linux
     protocol: efi
     path: boot():/something
     cmdline: quiet rootflags=subvol=/@/.snapshots/97/snapshot rw

/EFI fallback
comment: Default EFI loader
protocol: efi
path: boot():/EFI/BOOT/BOOTX64.EFI
`

func writeTemp(t *testing.T, name, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
	return path
}

func TestParseLimineConf(t *testing.T) {
	path := writeTemp(t, "limine.conf", sampleLimineConf)
	cfg, snaps, err := parseLimineConf(path)
	if err != nil {
		t.Fatalf("parseLimineConf: %v", err)
	}

	wantCfg := BootConfig{
		Path:           path,
		DefaultEntry:   "2",
		InterfaceBrand: "Omarchy Bootloader",
		HashMismatch:   "no",
		TermBackground: "1a1b26",
		Backdrop:       "1a1b26",
	}
	if !reflect.DeepEqual(cfg, wantCfg) {
		t.Errorf("BootConfig mismatch\n got: %+v\nwant: %+v", cfg, wantCfg)
	}

	wantSnaps := []BootSnapshot{
		{
			Number:    98,
			Timestamp: "2026-04-14 15:00:02",
			Type:      "timeline",
			Kernel:    "6.19.10-arch1-1",
			Subvol:    "/@/.snapshots/98/snapshot",
		},
		{
			Number:    97,
			Timestamp: "2026-04-14 14:00:06",
			Type:      "pre",
			Kernel:    "6.19.10-arch1-1",
			Subvol:    "/@/.snapshots/97/snapshot",
		},
	}
	if !reflect.DeepEqual(snaps, wantSnaps) {
		t.Errorf("snapshot list mismatch\n got: %+v\nwant: %+v", snaps, wantSnaps)
	}
}

func TestParseLimineConfLeavesSnapshotsSubtree(t *testing.T) {
	// Regression: after the Snapshots subtree ends, a sibling /EFI
	// fallback entry should not pollute the snapshot list.
	path := writeTemp(t, "limine.conf", sampleLimineConf)
	_, snaps, err := parseLimineConf(path)
	if err != nil {
		t.Fatalf("parseLimineConf: %v", err)
	}
	if len(snaps) != 2 {
		t.Fatalf("want 2 snapshots, got %d", len(snaps))
	}
	for _, s := range snaps {
		if s.Subvol == "" {
			t.Errorf("snapshot %+v missing subvol", s)
		}
	}
}

func TestParseShellAssignments(t *testing.T) {
	content := `# a comment
TARGET_OS_NAME="Omarchy"
ESP_PATH='/boot'
ENABLE_UKI=yes
# commented_key="ignored"
KERNEL_CMDLINE[default]+="cryptdevice=foo rw"
KERNEL_CMDLINE[default]+=" quiet splash"
`
	path := writeTemp(t, "defaults", content)
	kv, cmdline, err := parseShellAssignments(path)
	if err != nil {
		t.Fatalf("parseShellAssignments: %v", err)
	}
	wantKV := map[string]string{
		"TARGET_OS_NAME": "Omarchy",
		"ESP_PATH":       "/boot",
		"ENABLE_UKI":     "yes",
	}
	if !reflect.DeepEqual(kv, wantKV) {
		t.Errorf("kv mismatch\n got: %v\nwant: %v", kv, wantKV)
	}
	wantCmdline := []string{"cryptdevice=foo rw", " quiet splash"}
	if !reflect.DeepEqual(cmdline, wantCmdline) {
		t.Errorf("cmdline mismatch\n got: %v\nwant: %v", cmdline, wantCmdline)
	}
}

func TestExtractSubvol(t *testing.T) {
	line := `cmdline: quiet rootflags=subvol=/@/.snapshots/42/snapshot rw noacl`
	subvol, num := extractSubvol(line)
	if subvol != "/@/.snapshots/42/snapshot" {
		t.Errorf("subvol = %q", subvol)
	}
	if num != 42 {
		t.Errorf("num = %d", num)
	}
}

func TestExtractSubvolMissing(t *testing.T) {
	line := `cmdline: rw quiet`
	subvol, num := extractSubvol(line)
	if subvol != "" || num != 0 {
		t.Errorf("expected empty, got subvol=%q num=%d", subvol, num)
	}
}

func TestRewriteBootConfKeyExisting(t *testing.T) {
	in := "#timeout: 3\ndefault_entry: 2\ninterface_branding: Old\n\n/+Omarchy\ncomment: x\n"
	out := rewriteBootConfKey(in, "timeout", "5")
	if !strings.Contains(out, "timeout: 5") {
		t.Fatalf("timeout not set: %s", out)
	}
	if strings.Contains(out, "#timeout") {
		t.Fatalf("commented line not replaced: %s", out)
	}
	// Must not touch entries below.
	if !strings.Contains(out, "/+Omarchy") || !strings.Contains(out, "comment: x") {
		t.Fatalf("entry block lost: %s", out)
	}
}

func TestRewriteBootConfKeyAppend(t *testing.T) {
	in := "default_entry: 2\n\n/+Omarchy\n"
	out := rewriteBootConfKey(in, "timeout", "5")
	if !strings.Contains(out, "timeout: 5") {
		t.Fatalf("timeout not appended: %s", out)
	}
	// New key must land BEFORE the entry block.
	if strings.Index(out, "timeout: 5") > strings.Index(out, "/+Omarchy") {
		t.Fatalf("key appended after entries: %s", out)
	}
}

func TestRewriteBootConfKeyDoesNotTouchEntries(t *testing.T) {
	in := "default_entry: 1\n/+Omarchy\ntimeout: bogus\n"
	out := rewriteBootConfKey(in, "timeout", "5")
	// The bogus "timeout:" inside the entry must NOT be replaced.
	if !strings.Contains(out, "timeout: bogus") {
		t.Fatalf("entry-local timeout was rewritten: %s", out)
	}
	if !strings.Contains(out, "timeout: 5") {
		t.Fatalf("timeout not appended: %s", out)
	}
}

func TestRewriteShellAssignmentExisting(t *testing.T) {
	in := `TARGET_OS_NAME="Old"` + "\n" + `ESP_PATH=/boot` + "\n"
	out := rewriteShellAssignment(in, "TARGET_OS_NAME", "New")
	if !strings.Contains(out, `TARGET_OS_NAME="New"`) {
		t.Fatalf("not replaced: %s", out)
	}
	if strings.Contains(out, "Old") {
		t.Fatalf("old value still present: %s", out)
	}
}

func TestRewriteShellAssignmentUncomments(t *testing.T) {
	in := `#TARGET_OS_NAME="Arch Linux"` + "\n"
	out := rewriteShellAssignment(in, "TARGET_OS_NAME", "Omarchy")
	if !strings.Contains(out, `TARGET_OS_NAME="Omarchy"`) {
		t.Fatalf("not uncommented: %s", out)
	}
	if strings.Contains(out, `#TARGET_OS_NAME`) {
		t.Fatalf("still commented: %s", out)
	}
}

func TestRewriteShellAssignmentAppend(t *testing.T) {
	in := "ESP_PATH=/boot\n"
	out := rewriteShellAssignment(in, "TARGET_OS_NAME", "Omarchy")
	if !strings.Contains(out, `TARGET_OS_NAME="Omarchy"`) {
		t.Fatalf("not appended: %s", out)
	}
}

func TestRewriteShellCmdline(t *testing.T) {
	in := `TARGET_OS_NAME="Omarchy"
KERNEL_CMDLINE[default]+="old-a"
KERNEL_CMDLINE[default]+=" old-b"
ENABLE_UKI=yes
`
	out := rewriteShellCmdline(in, []string{"new-a", "new-b", "new-c"})
	if strings.Contains(out, "old-a") || strings.Contains(out, "old-b") {
		t.Fatalf("old cmdline still present: %s", out)
	}
	want := []string{
		`KERNEL_CMDLINE[default]+="new-a"`,
		`KERNEL_CMDLINE[default]+="new-b"`,
		`KERNEL_CMDLINE[default]+="new-c"`,
	}
	for _, w := range want {
		if !strings.Contains(out, w) {
			t.Errorf("missing %q:\n%s", w, out)
		}
	}
	// Ordering: new cmdline block must sit between TARGET_OS_NAME and ENABLE_UKI.
	if strings.Index(out, "new-a") < strings.Index(out, "TARGET_OS_NAME") {
		t.Errorf("cmdline moved above TARGET_OS_NAME:\n%s", out)
	}
	if strings.Index(out, "new-c") > strings.Index(out, "ENABLE_UKI") {
		t.Errorf("cmdline moved below ENABLE_UKI:\n%s", out)
	}
}

func TestRewriteShellCmdlineAppend(t *testing.T) {
	in := "ESP_PATH=/boot\n"
	out := rewriteShellCmdline(in, []string{"rw", "quiet"})
	if !strings.Contains(out, `KERNEL_CMDLINE[default]+="rw"`) {
		t.Fatalf("rw not appended: %s", out)
	}
	if !strings.Contains(out, `KERNEL_CMDLINE[default]+="quiet"`) {
		t.Fatalf("quiet not appended: %s", out)
	}
}
