package bus

// Subject constants for the dark message bus. The naming convention is:
//
//	dark.<domain>.<resource>         events, server -> clients
//	dark.cmd.<domain>.<verb>         commands, client -> server (request/reply)
//	dark.daemon.<event>              daemon lifecycle
//
// Clients should use wildcard subscriptions where it makes sense
// (e.g. dark.> for everything, dark.wifi.> for all Wi-Fi events).
const (
	SubjectDaemonHeartbeat = "dark.daemon.heartbeat"

	SubjectSystemInfo    = "dark.system.info"
	SubjectSystemInfoCmd = "dark.cmd.system.info"

	SubjectWifiAdapters      = "dark.wifi.adapters"
	SubjectWifiAdaptersCmd   = "dark.cmd.wifi.adapters"
	SubjectWifiScanCmd       = "dark.cmd.wifi.scan"
	SubjectWifiConnectCmd    = "dark.cmd.wifi.connect"
	SubjectWifiDisconnectCmd = "dark.cmd.wifi.disconnect"
	SubjectWifiForgetCmd     = "dark.cmd.wifi.forget"
	SubjectWifiPowerCmd         = "dark.cmd.wifi.power"
	SubjectWifiAutoconnectCmd   = "dark.cmd.wifi.autoconnect"
	SubjectWifiConnectHiddenCmd = "dark.cmd.wifi.connect_hidden"
	SubjectWifiAPStartCmd       = "dark.cmd.wifi.ap_start"
	SubjectWifiAPStopCmd        = "dark.cmd.wifi.ap_stop"

	SubjectBluetoothAdapters       = "dark.bluetooth.adapters"
	SubjectBluetoothAdaptersCmd    = "dark.cmd.bluetooth.adapters"
	SubjectBluetoothPowerCmd       = "dark.cmd.bluetooth.power"
	SubjectBluetoothDiscoverOnCmd  = "dark.cmd.bluetooth.discovery_start"
	SubjectBluetoothDiscoverOffCmd = "dark.cmd.bluetooth.discovery_stop"
	SubjectBluetoothConnectCmd     = "dark.cmd.bluetooth.connect"
	SubjectBluetoothDisconnectCmd  = "dark.cmd.bluetooth.disconnect"
	SubjectBluetoothPairCmd        = "dark.cmd.bluetooth.pair"
	SubjectBluetoothRemoveCmd      = "dark.cmd.bluetooth.remove"
	SubjectBluetoothTrustCmd        = "dark.cmd.bluetooth.trust"
	SubjectBluetoothDiscoverableCmd = "dark.cmd.bluetooth.discoverable"
	SubjectBluetoothAliasCmd        = "dark.cmd.bluetooth.alias"
	SubjectBluetoothPairableCmd            = "dark.cmd.bluetooth.pairable"
	SubjectBluetoothBlockCmd               = "dark.cmd.bluetooth.block"
	SubjectBluetoothCancelPairCmd          = "dark.cmd.bluetooth.cancel_pair"
	SubjectBluetoothDiscoverableTimeoutCmd = "dark.cmd.bluetooth.discoverable_timeout"
	SubjectBluetoothDiscoveryFilterCmd     = "dark.cmd.bluetooth.discovery_filter"

	SubjectAudioDevices         = "dark.audio.devices"
	SubjectAudioDevicesCmd      = "dark.cmd.audio.devices"
	SubjectAudioSinkVolumeCmd    = "dark.cmd.audio.sink_volume"
	SubjectAudioSinkMuteCmd      = "dark.cmd.audio.sink_mute"
	SubjectAudioSinkBalanceCmd   = "dark.cmd.audio.sink_balance"
	SubjectAudioSourceVolumeCmd  = "dark.cmd.audio.source_volume"
	SubjectAudioSourceMuteCmd    = "dark.cmd.audio.source_mute"
	SubjectAudioSourceBalanceCmd = "dark.cmd.audio.source_balance"
	SubjectAudioDefaultSinkCmd   = "dark.cmd.audio.default_sink"
	SubjectAudioDefaultSourceCmd = "dark.cmd.audio.default_source"
	SubjectAudioCardProfileCmd       = "dark.cmd.audio.card_profile"
	SubjectAudioSinkPortCmd          = "dark.cmd.audio.sink_port"
	SubjectAudioSourcePortCmd        = "dark.cmd.audio.source_port"
	SubjectAudioSinkInputVolumeCmd   = "dark.cmd.audio.sink_input_volume"
	SubjectAudioSinkInputMuteCmd     = "dark.cmd.audio.sink_input_mute"
	SubjectAudioSinkInputMoveCmd     = "dark.cmd.audio.sink_input_move"
	SubjectAudioSourceOutputVolumeCmd = "dark.cmd.audio.source_output_volume"
	SubjectAudioSourceOutputMuteCmd  = "dark.cmd.audio.source_output_mute"
	SubjectAudioSourceOutputMoveCmd  = "dark.cmd.audio.source_output_move"
	SubjectAudioSinkInputKillCmd     = "dark.cmd.audio.sink_input_kill"
	SubjectAudioSourceOutputKillCmd  = "dark.cmd.audio.source_output_kill"
	SubjectAudioSuspendSinkCmd       = "dark.cmd.audio.suspend_sink"
	SubjectAudioSuspendSourceCmd     = "dark.cmd.audio.suspend_source"
	SubjectAudioLevels               = "dark.audio.levels"

	SubjectNetworkSnapshot         = "dark.network.snapshot"
	SubjectNetworkSnapshotCmd      = "dark.cmd.network.snapshot"
	SubjectNetworkReconfigureCmd   = "dark.cmd.network.reconfigure"
	SubjectNetworkConfigureIPv4Cmd = "dark.cmd.network.configure_ipv4"
	SubjectNetworkResetCmd         = "dark.cmd.network.reset"
	SubjectNetworkAirplaneCmd      = "dark.cmd.network.airplane"

	SubjectDisplayMonitors       = "dark.display.monitors"
	SubjectDisplayMonitorsCmd    = "dark.cmd.display.monitors"
	SubjectDisplayResolutionCmd  = "dark.cmd.display.resolution"
	SubjectDisplayScaleCmd       = "dark.cmd.display.scale"
	SubjectDisplayTransformCmd   = "dark.cmd.display.transform"
	SubjectDisplayPositionCmd    = "dark.cmd.display.position"
	SubjectDisplayDpmsCmd        = "dark.cmd.display.dpms"
	SubjectDisplayVrrCmd         = "dark.cmd.display.vrr"
	SubjectDisplayMirrorCmd      = "dark.cmd.display.mirror"
	SubjectDisplayToggleCmd      = "dark.cmd.display.toggle"
	SubjectDisplayIdentifyCmd      = "dark.cmd.display.identify"
	SubjectDisplayBrightnessCmd    = "dark.cmd.display.brightness"
	SubjectDisplayKbdBrightnessCmd = "dark.cmd.display.kbd_brightness"
	SubjectDisplayNightLightCmd     = "dark.cmd.display.night_light"
	SubjectDisplayGammaCmd          = "dark.cmd.display.gamma"
	SubjectDisplaySaveProfileCmd    = "dark.cmd.display.save_profile"
	SubjectDisplayApplyProfileCmd   = "dark.cmd.display.apply_profile"
	SubjectDisplayDeleteProfileCmd  = "dark.cmd.display.delete_profile"
	SubjectDisplayGPUModeCmd        = "dark.cmd.display.gpu_mode"

	SubjectDateTimeSnapshot    = "dark.datetime.snapshot"
	SubjectDateTimeSnapshotCmd = "dark.cmd.datetime.snapshot"
	SubjectDateTimeTZCmd       = "dark.cmd.datetime.timezone"
	SubjectDateTimeNTPCmd      = "dark.cmd.datetime.ntp"
	SubjectDateTimeFormatCmd   = "dark.cmd.datetime.format"
	SubjectDateTimeSetTimeCmd  = "dark.cmd.datetime.set_time"
	SubjectDateTimeRTCCmd      = "dark.cmd.datetime.rtc"

	SubjectInputSnapshot       = "dark.input.snapshot"
	SubjectInputSnapshotCmd    = "dark.cmd.input.snapshot"
	SubjectInputRepeatRateCmd  = "dark.cmd.input.repeat_rate"
	SubjectInputRepeatDelayCmd = "dark.cmd.input.repeat_delay"
	SubjectInputSensitivityCmd = "dark.cmd.input.sensitivity"
	SubjectInputNatScrollCmd        = "dark.cmd.input.natural_scroll"
	SubjectInputScrollFactorCmd    = "dark.cmd.input.scroll_factor"
	SubjectInputKBLayoutCmd        = "dark.cmd.input.kb_layout"
	SubjectInputAccelProfileCmd    = "dark.cmd.input.accel_profile"
	SubjectInputForceNoAccelCmd    = "dark.cmd.input.force_no_accel"
	SubjectInputLeftHandedCmd      = "dark.cmd.input.left_handed"
	SubjectInputDisableTypingCmd   = "dark.cmd.input.disable_while_typing"
	SubjectInputTapToClickCmd      = "dark.cmd.input.tap_to_click"
	SubjectInputTapAndDragCmd      = "dark.cmd.input.tap_and_drag"
	SubjectInputDragLockCmd        = "dark.cmd.input.drag_lock"
	SubjectInputMiddleBtnCmd       = "dark.cmd.input.middle_button_emu"
	SubjectInputClickfingerCmd     = "dark.cmd.input.clickfinger"

	SubjectNotifySnapshot    = "dark.notify.snapshot"
	SubjectNotifySnapshotCmd = "dark.cmd.notify.snapshot"
	SubjectNotifyDNDCmd       = "dark.cmd.notify.dnd"
	SubjectNotifyDismissCmd   = "dark.cmd.notify.dismiss"
	SubjectNotifyAnchorCmd    = "dark.cmd.notify.anchor"
	SubjectNotifyTimeoutCmd   = "dark.cmd.notify.timeout"
	SubjectNotifyWidthCmd      = "dark.cmd.notify.width"
	SubjectNotifyLayerCmd      = "dark.cmd.notify.layer"
	SubjectNotifySoundCmd      = "dark.cmd.notify.sound"
	SubjectNotifyAddRuleCmd    = "dark.cmd.notify.add_rule"
	SubjectNotifyRemoveRuleCmd = "dark.cmd.notify.remove_rule"

	SubjectPowerSnapshot    = "dark.power.snapshot"
	SubjectPowerSnapshotCmd = "dark.cmd.power.snapshot"
	SubjectPowerProfileCmd  = "dark.cmd.power.profile"
	SubjectPowerGovernorCmd  = "dark.cmd.power.governor"
	SubjectPowerEPPCmd       = "dark.cmd.power.epp"
	SubjectPowerIdleCmd      = "dark.cmd.power.idle"
	SubjectPowerIdleRunningCmd = "dark.cmd.power.idle_running"
	SubjectPowerButtonCmd    = "dark.cmd.power.button"

	SubjectAppstoreCatalog    = "dark.appstore.catalog"
	SubjectAppstoreCatalogCmd = "dark.cmd.appstore.catalog"
	SubjectAppstoreSearchCmd  = "dark.cmd.appstore.search"
	SubjectAppstoreDetailCmd  = "dark.cmd.appstore.detail"
	SubjectAppstoreRefreshCmd = "dark.cmd.appstore.refresh"
	SubjectAppstoreInstallCmd = "dark.cmd.appstore.install"
	SubjectAppstoreRemoveCmd  = "dark.cmd.appstore.remove"
	SubjectAppstoreUpgradeCmd = "dark.cmd.appstore.upgrade"

	SubjectPrivacySnapshot    = "dark.privacy.snapshot"
	SubjectPrivacySnapshotCmd = "dark.cmd.privacy.snapshot"
	SubjectPrivacyIdleCmd     = "dark.cmd.privacy.idle"
	SubjectPrivacyDNSTLSCmd   = "dark.cmd.privacy.dns_tls"
	SubjectPrivacyDNSSECCmd   = "dark.cmd.privacy.dnssec"
	SubjectPrivacyFirewallCmd = "dark.cmd.privacy.firewall"
	SubjectPrivacySSHCmd      = "dark.cmd.privacy.ssh"
	SubjectPrivacyClearCmd    = "dark.cmd.privacy.clear_recent"
	SubjectPrivacyLocationCmd = "dark.cmd.privacy.location"
	SubjectPrivacyMACCmd      = "dark.cmd.privacy.mac_random"
	SubjectPrivacyIndexerCmd  = "dark.cmd.privacy.indexer"
	SubjectPrivacyCoredumpCmd = "dark.cmd.privacy.coredump"

	SubjectUsersSnapshot    = "dark.users.snapshot"
	SubjectUsersSnapshotCmd = "dark.cmd.users.snapshot"
	SubjectUsersAddCmd      = "dark.cmd.users.add"
	SubjectUsersRemoveCmd   = "dark.cmd.users.remove"
	SubjectUsersShellCmd    = "dark.cmd.users.shell"
	SubjectUsersCommentCmd  = "dark.cmd.users.comment"
	SubjectUsersLockCmd     = "dark.cmd.users.lock"
	SubjectUsersGroupCmd    = "dark.cmd.users.group"
	SubjectUsersAdminCmd    = "dark.cmd.users.admin"
	SubjectUsersPasswdCmd   = "dark.cmd.users.passwd"
	SubjectUsersElevateCmd  = "dark.cmd.users.elevate"

	SubjectAppearanceSnapshot    = "dark.appearance.snapshot"
	SubjectAppearanceSnapshotCmd = "dark.cmd.appearance.snapshot"
	SubjectAppearanceGapsInCmd   = "dark.cmd.appearance.gaps_in"
	SubjectAppearanceGapsOutCmd  = "dark.cmd.appearance.gaps_out"
	SubjectAppearanceBorderCmd   = "dark.cmd.appearance.border"
	SubjectAppearanceRoundingCmd = "dark.cmd.appearance.rounding"
	SubjectAppearanceBlurCmd     = "dark.cmd.appearance.blur"
	SubjectAppearanceBlurSizeCmd = "dark.cmd.appearance.blur_size"
	SubjectAppearanceBlurPassCmd = "dark.cmd.appearance.blur_passes"
	SubjectAppearanceAnimCmd     = "dark.cmd.appearance.anim"
	SubjectAppearanceThemeCmd      = "dark.cmd.appearance.theme"
	SubjectAppearanceFontCmd       = "dark.cmd.appearance.font"
	SubjectAppearanceFontSizeCmd   = "dark.cmd.appearance.font_size"
	SubjectAppearanceBackgroundCmd = "dark.cmd.appearance.background"

	SubjectKeybindSnapshot    = "dark.keybind.snapshot"
	SubjectKeybindSnapshotCmd = "dark.cmd.keybind.snapshot"
	SubjectKeybindAddCmd      = "dark.cmd.keybind.add"
	SubjectKeybindUpdateCmd   = "dark.cmd.keybind.update"
	SubjectKeybindRemoveCmd   = "dark.cmd.keybind.remove"

	SubjectUpdateSnapshot    = "dark.update.snapshot"
	SubjectUpdateSnapshotCmd = "dark.cmd.update.snapshot"
	SubjectUpdateRunCmd      = "dark.cmd.update.run"
	SubjectUpdateChannelCmd  = "dark.cmd.update.channel"

	SubjectFirmwareSnapshot    = "dark.firmware.snapshot"
	SubjectFirmwareSnapshotCmd = "dark.cmd.firmware.snapshot"

	SubjectLimineSnapshot         = "dark.limine.snapshot"
	SubjectLimineSnapshotCmd      = "dark.cmd.limine.snapshot"
	SubjectLimineCreateCmd        = "dark.cmd.limine.create"
	SubjectLimineDeleteCmd        = "dark.cmd.limine.delete"
	SubjectLimineSyncCmd          = "dark.cmd.limine.sync"
	SubjectLimineDefaultEntryCmd  = "dark.cmd.limine.default_entry"
	SubjectLimineBootConfigCmd    = "dark.cmd.limine.boot_config"
	SubjectLimineSyncConfigCmd    = "dark.cmd.limine.sync_config"
	SubjectLimineOmarchyConfigCmd = "dark.cmd.limine.omarchy_config"
	SubjectLimineKernelCmdlineCmd = "dark.cmd.limine.kernel_cmdline"

	SubjectScreensaverSnapshot      = "dark.screensaver.snapshot"
	SubjectScreensaverSnapshotCmd   = "dark.cmd.screensaver.snapshot"
	SubjectScreensaverSetEnabledCmd = "dark.cmd.screensaver.set_enabled"
	SubjectScreensaverSetContentCmd = "dark.cmd.screensaver.set_content"
	SubjectScreensaverPreviewCmd    = "dark.cmd.screensaver.preview"

	SubjectTopBarSnapshot       = "dark.topbar.snapshot"
	SubjectTopBarSnapshotCmd    = "dark.cmd.topbar.snapshot"
	SubjectTopBarSetRunningCmd  = "dark.cmd.topbar.set_running"
	SubjectTopBarRestartCmd     = "dark.cmd.topbar.restart"
	SubjectTopBarResetCmd       = "dark.cmd.topbar.reset"
	SubjectTopBarSetPositionCmd = "dark.cmd.topbar.set_position"
	SubjectTopBarSetLayerCmd    = "dark.cmd.topbar.set_layer"
	SubjectTopBarSetHeightCmd   = "dark.cmd.topbar.set_height"
	SubjectTopBarSetSpacingCmd  = "dark.cmd.topbar.set_spacing"
	SubjectTopBarSetConfigCmd   = "dark.cmd.topbar.set_config"
	SubjectTopBarSetStyleCmd    = "dark.cmd.topbar.set_style"

	SubjectWorkspacesSnapshot            = "dark.workspaces.snapshot"
	SubjectWorkspacesSnapshotCmd         = "dark.cmd.workspaces.snapshot"
	SubjectWorkspacesSwitchCmd           = "dark.cmd.workspaces.switch"
	SubjectWorkspacesRenameCmd           = "dark.cmd.workspaces.rename"
	SubjectWorkspacesMoveToMonitorCmd    = "dark.cmd.workspaces.move_to_monitor"
	SubjectWorkspacesSetLayoutCmd        = "dark.cmd.workspaces.set_layout"
	SubjectWorkspacesSetDefaultLayoutCmd = "dark.cmd.workspaces.set_default_layout"
	SubjectWorkspacesSetDwindleOptionCmd = "dark.cmd.workspaces.set_dwindle_option"
	SubjectWorkspacesSetMasterOptionCmd  = "dark.cmd.workspaces.set_master_option"
	SubjectWorkspacesSetCursorWarpCmd    = "dark.cmd.workspaces.set_cursor_warp"
	SubjectWorkspacesSetAnimationsCmd    = "dark.cmd.workspaces.set_animations"
	SubjectWorkspacesSetHideSpecialCmd   = "dark.cmd.workspaces.set_hide_special"

	SubjectDarkUpdateSnapshot    = "dark.updateself.snapshot"
	SubjectDarkUpdateSnapshotCmd = "dark.cmd.updateself.snapshot"
	SubjectDarkUpdateCheckCmd    = "dark.cmd.updateself.check"
	SubjectDarkUpdateApplyCmd    = "dark.cmd.updateself.apply"

	SubjectSSHSnapshot              = "dark.ssh.snapshot"
	SubjectSSHSnapshotCmd           = "dark.cmd.ssh.snapshot"
	SubjectSSHGenerateKeyCmd        = "dark.cmd.ssh.generate_key"
	SubjectSSHDeleteKeyCmd          = "dark.cmd.ssh.delete_key"
	SubjectSSHChangePassphraseCmd   = "dark.cmd.ssh.change_passphrase"
	SubjectSSHAgentStartCmd         = "dark.cmd.ssh.agent_start"
	SubjectSSHAgentStopCmd          = "dark.cmd.ssh.agent_stop"
	SubjectSSHAgentAddCmd           = "dark.cmd.ssh.agent_add"
	SubjectSSHAgentRemoveCmd        = "dark.cmd.ssh.agent_remove"
	SubjectSSHAgentRemoveAllCmd     = "dark.cmd.ssh.agent_remove_all"
	SubjectSSHSaveHostCmd           = "dark.cmd.ssh.save_host"
	SubjectSSHDeleteHostCmd         = "dark.cmd.ssh.delete_host"
	SubjectSSHScanHostCmd           = "dark.cmd.ssh.scan_host"
	SubjectSSHRemoveKnownHostCmd    = "dark.cmd.ssh.remove_known_host"
	SubjectSSHAddAuthorizedKeyCmd   = "dark.cmd.ssh.add_authorized_key"
	SubjectSSHRemoveAuthorizedKeyCmd = "dark.cmd.ssh.remove_authorized_key"
	SubjectSSHSaveServerConfigCmd    = "dark.cmd.ssh.save_server_config"
	SubjectSSHRestoreBackupCmd       = "dark.cmd.ssh.restore_backup"

	SubjectScriptingListCmd       = "dark.cmd.scripting.list"
	SubjectScriptingRegistryCmd   = "dark.cmd.scripting.registry"
	SubjectScriptingAPICatalogCmd = "dark.cmd.scripting.api_catalog"
	SubjectScriptingMCPCatalogCmd = "dark.cmd.scripting.mcp_catalog"
	SubjectScriptingReadCmd       = "dark.cmd.scripting.read"
	SubjectScriptingSaveCmd       = "dark.cmd.scripting.save"
	SubjectScriptingDeleteCmd     = "dark.cmd.scripting.delete"
	SubjectScriptingCallCmd       = "dark.cmd.scripting.call"
	SubjectScriptingReloadCmd     = "dark.cmd.scripting.reload"
)
